#
# dhForum build config for Travis CI
#

language: php
php: 5.5
cache:
    directories: vendor
before_install: phpenv config-rm xdebug.ini
install: composer install --no-progress --no-suggest --no-interaction --prefer-dist --optimize-autoloader
script: composer dh:test
